[package]
name = "helium"
version = "0.1.0"
edition = "2021"

[dependencies]
helium_ecs = { version = "0.1.0", path = "../helium_ecs" }
helium_renderer = { path = "../helium_renderer" }
pollster = "0.4.0"
pretty_env_logger = "0.5.0"
