[package]
name = "helium"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
helium_ecs = { version = "0.1.0", path = "../helium_ecs" }
helium_renderer = { path = "../helium_renderer" }
pretty_env_logger = "0.5.0"
smol = "2.0.2"
