[package]
name = "helium_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.21.0"
cgmath = "0.18.0"
image = "0.25.5"
log = "0.4.25"
smol = "2.0.2"
wgpu = "24.0.0"
winit = { version = "0.30.8", features = ["rwh_05"] }
helium_io = { path = "../helium_io" }
wgpu_text = "0.9.2"
